### ISSUE TITLE
Item 2: preprocessing

### ISSUE THREAD

**Issue by aisolab** [lassl/scheduler#4]
## 개요
RoBERTa가 full sentence (512) 기준으로 training example을 미리 만들어둔다. 실제 나중에 masking을 하는 것을 아래의 class를 이용한다고 생각한다.

- https://github.com/huggingface/transformers/blob/26212c14e5570aff40b90c11495d97dada4272fb/src/transformers/data/data_collator.py#L302

이번 회차의 팀 구성은 아래와 같다.

- t1
  - **김보섭**, 김대규, 문영기, 류인제
- t2
  - **김형석**, 강재호, 김형준, 류민호
- t3
  - **유원준**, 고우영, 백혜림, 최태균

임시로 `preprocessing`이라는 repository에서 진행하도록 한다.

cc: @pretraining/authors

**Comment by IJryou** [comment]
- DataCollatorForLanguageModeling를 활용할 수 있는 case 를 만들어 본다
- https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_mlm.py
- 훈련할 때 문장길이를 조절할 수 있도록 구현 (full sentence 고려)
